//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peliculas.WS.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public System.Guid ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> AnioEstreno { get; set; }
        public string Pais { get; set; }
        public string Categoria { get; set; }
        public string Idioma { get; set; }
    }
}
